name: check
# This workflow runs whenever a PR is opened or updated, or a commit is pushed
# to main. It runs several checks:
# - fmt: checks that the code is formatted according to `rustfmt`.
# - clippy: checks that the code does not contain any `clippy` warnings.
# - doc: checks that the code can be documented without errors.
# - typos: checks for typos across the repo.

on:
  push:
    branches: [main]
  pull_request:

# If new code is pushed to a PR branch, then cancel in progress workflows for
# that PR. Ensures that we don't waste CI time, and returns results quicker.
concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    name: fmt
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: cargo fmt
        run: cargo fmt --all --check

  clippy:
    runs-on: ubuntu-latest
    name: clippy
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - name: cargo fmt
        run: cargo clippy -- -D warnings

  doc:
    # Run docs generation on nightly rather than stable. This enables features
    # like https://doc.rust-lang.org/beta/unstable-book/language-features/doc-cfg.html
    # which allows an API be documented as only available in some specific
    # platforms.
    runs-on: ubuntu-latest
    name: doc
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install nightly
        uses: dtolnay/rust-toolchain@nightly
      - name: cargo doc
        run: cargo doc --no-deps --all-features
        env:
          RUSTDOCFLAGS: --cfg docsrs

  typos:
    runs-on: ubuntu-latest
    name: typos
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
      - name: Check spelling of files in the workspace
        uses: crate-ci/typos@v1.28.4

